Set-PSFConfig -Module AzOps -Name AzOps.DefaultDeploymentRegion -Value northeurope -Initialize -Validation string -Description 'Default deployment region for state deployments (ARM region, not region where a resource is deployed)'
Set-PSFConfig -Module AzOps -Name AzOps.EnrollmentAccountPrincipalName -Value '' -Initialize -Validation string -Description 'add text'
Set-PSFConfig -Module AzOps -Name AzOps.ExcludedSubOffer -Value 'AzurePass_2014-09-01','FreeTrial_2014-09-01','AAD_2015-09-01' -Initialize -Validation stringarray -Description 'Excluded QuotaIDs as per https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/understand-cost-mgt-data#supported-microsoft-azure-offers'
Set-PSFConfig -Module AzOps -Name AzOps.ExcludedSubState -Value 'Disabled','Deleted','Warned','Expired' -Initialize -Validation stringarray -Description 'Excluded subscription states as per https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/list#subscriptionstate'
Set-PSFConfig -Module AzOps -Name AzOps.ExportRawTemplate -Value $false -Initialize -Validation bool -Description 'add text'
Set-PSFConfig -Module AzOps -Name AzOps.GeneralizeTemplates -Value $false -Initialize -Validation bool -Description 'Invalidates cache and ensures that Management Groups and Subscriptions are re-discovered'
Set-PSFConfig -Module AzOps -Name AzOps.IgnoreContextCheck -Value $false -Initialize -Validation bool -Description 'If set to $true, skip AAD tenant validation == 1'
Set-PSFConfig -Module AzOps -Name AzOps.InvalidateCache -Value $true -Initialize -Validation bool -Description 'Invalidates cache and ensures that Management Groups and Subscriptions are re-discovered'
Set-PSFConfig -Module AzOps -Name AzOps.MainTemplate -Value "$PSScriptRoot\..\..\template\template.json" -Initialize -Validation string -Description 'Main template json'
Set-PSFConfig -Module AzOps -Name AzOps.OfferType -Value 'MS-AZR-0017P' -Initialize -Validation string -Description 'add text'
Set-PSFConfig -Module AzOps -Name AzOps.PartialMgDiscoveryRoot -Value @() -Initialize -Validation stringarray -Description 'Used in combination with AZOPS_SUPPORT_PARTIAL_MG_DISCOVERY, example value: "Contoso","Tailspin","Management"'
Set-PSFConfig -Module AzOps -Name AzOps.SkipPolicy -Value $false -Initialize -Validation bool -Description 'add text'
Set-PSFConfig -Module AzOps -Name AzOps.SkipResourceGroup -Value $true -Initialize -Validation bool -Description 'add text'
Set-PSFConfig -Module AzOps -Name AzOps.SkipRole -Value $false -Initialize -Validation bool -Description 'add text'
Set-PSFConfig -Module AzOps -Name AzOps.State -Value (Join-Path $pwd -ChildPath "azops") -Initialize -Validation string -Description 'Folder to store AzOpsState artefact'
Set-PSFConfig -Module AzOps -Name AzOps.StateConfig -Value "$PSScriptRoot\..\AzOpsStateConfig.json" -Initialize -Validation string -Description 'Configuration file for resource serialization'
Set-PSFConfig -Module AzOps -Name AzOps.StrictMode -Value $false -Initialize -Validation bool -Description 'add text'
Set-PSFConfig -Module AzOps -Name AzOps.SupportPartialMgDiscovery -Value $false -Initialize -Validation bool -Description 'Enable partial discovery'
Set-PSFConfig -Module AzOps -Name AzOps.ThrottleLimit -Value 10 -Initialize -Validation integer -Description 'Throttle limit used in Foreach-Object -Parallel for resource/subscription discovery'