# GitHub Actions
Set-PSFConfig -Module AzOps -Name Actions.ApiUrl -Value '' -Initialize -Validation string -Description 'Built-in env var'
Set-PSFConfig -Module AzOps -Name Actions.AutoMerge -Value $true -Initialize -Validation bool -Description 'Auto merge pull requests for pull workflow'
Set-PSFConfig -Module AzOps -Name Actions.BaseRef -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Actions.Comments -Value '' -Initialize -Validation string -Description 'Built-in env var'
Set-PSFConfig -Module AzOps -Name Actions.Email -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Actions.HeadRef -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Actions.PullRequest -Value '' -Initialize -Validation string -Description 'Pull Request title'
Set-PSFConfig -Module AzOps -Name Actions.Repository -Value '' -Initialize -Validation string -Description 'Built-in env var'
Set-PSFConfig -Module AzOps -Name Actions.Token -Value '' -Initialize -Validation string -Description 'Built-in env var'
Set-PSFConfig -Module AzOps -Name Actions.Username -Value '' -Initialize -Validation string -Description '-'
