Set-PSFConfig -Module AzOps -Name Github.ApiUrl -Value '' -Initialize -Validation string -Description 'Built-in env var'
Set-PSFConfig -Module AzOps -Name Github.AutoMerge -Value $true -Initialize -Validation bool -Description 'Auto merge pull requests for pull workflow'
Set-PSFConfig -Module AzOps -Name Github.BaseRef -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Github.Comments -Value '' -Initialize -Validation string -Description 'Built-in env var'
Set-PSFConfig -Module AzOps -Name Github.Email -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Github.HeadRef -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Github.PullRequest -Value '' -Initialize -Validation string -Description 'Pull Request title'
Set-PSFConfig -Module AzOps -Name Github.Repository -Value '' -Initialize -Validation string -Description 'Built-in env var'
Set-PSFConfig -Module AzOps -Name Github.Token -Value '' -Initialize -Validation string -Description 'Built-in env var'
Set-PSFConfig -Module AzOps -Name Github.Username -Value '' -Initialize -Validation string -Description '-'