# Azure Pipelines
Set-PSFConfig -Module AzOps -Name Pipelines.ApiUrl -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.AutoMerge -Value $true -Initialize -Validation bool -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.BaseRef -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.Email -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.HeadRef -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.ProjectId -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.PullRequest -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.PullRequestId -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.Repository -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.Token -Value '' -Initialize -Validation string -Description '-'
Set-PSFConfig -Module AzOps -Name Pipelines.Username -Value '' -Initialize -Validation string -Description '-'
