---
name: 'AzOps - Sync'

#
# Triggers
#

trigger: none

#
# Schedule
# Adjust frequency based on your organization need
#

schedules:
  - cron: "0 0 * * *"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: "ubuntu-20.04"

jobs:

  - job: sync
    displayName: 'Sync'
    steps:

      #
      # Checkout
      # Checks-out the repository
      #

      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      #
      # Configure
      # Set global options
      #

      - task: Bash@3
        displayName: "Configure"
        inputs:
          targetType: "inline"
          script: |
            git config user.name "Azure DevOps"
            git config user.email "azuredevops@microsoft.com"

      #
      # Sync
      # Fetch upstream changes
      #

      - task: Bash@3
        displayName: "Sync"
        inputs:
          targetType: "inline"
          script: |
            git remote -v
            git remote remove origin
            git remote add origin $(Build.Repository.Uri)
            git remote add upstream https://github.com/Azure/AzOps.git
            git fetch upstream
            git merge upstream/dev --no-edit
            git push origin HEAD:dev
