trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - "**/*.md"
      - "**/*.yml"

variables:
  ContainerRegistry: AzOpsRegistry
  ContainerTag: <replaceme>
  ContainerRepository: <replaceme>/<replaceme>
  DockerVersion: '19.03.11'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: DockerInstaller@0
  displayName: Install Docker
  inputs:
    dockerVersion: $(DockerVersion)
    releaseType: stable

- task: Docker@2
  displayName: Docker login
  inputs:
    command: login
    containerRegistry: $(ContainerRegistry)

- task: Docker@2
  displayName: Build and push image
  inputs:
    command: buildAndPush
    containerRegistry: $(ContainerRegistry)
    Dockerfile: ./Dockerfile
    repository: $(ContainerRepository)
    tags: |
      $(Build.BuildId)
      $(ContainerTag)

- task: Docker@2
  displayName: Docker logout
  condition: true
  inputs:
    command: logout
    containerRegistry: $(ContainerRegistry)
