---
name: Code Review (push)

######################################################
# Start the job on push for all branches except main #
######################################################
on:
  push:
    branches-ignore: [main]

###############
# Set the Job #
###############
jobs:

  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Super-Linter
      # Need to pull "latest" until a new release tag includes arm-ttk linter
      uses: docker://github/super-linter:latest
      env:
        # Only lint code which has been added or modified on push
        VALIDATE_ALL_CODEBASE: false
        # Temporarily allowing linter to complete with exit code 0 even
        # if errors were detected while working on code clean-up
        DISABLE_ERRORS: true

...

---
name: Code Review (pull_request)

##########################################
# Start the job on pull requests to main #
##########################################
on:
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:

  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Super-Linter
      # Need to pull "latest" until a new release tag includes arm-ttk linter
      uses: docker://github/super-linter:latest
      env:
        # Lint all code on pull_request
        VALIDATE_ALL_CODEBASE: true
        # Temporarily allowing linter to complete with exit code 0 even
        # if errors were detected while working on code clean-up
        DISABLE_ERRORS: true

...
