---
name: "Dependencies"

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

env:
  #
  # Branch Name
  # As part of the Dependencies workflow we create a temporary branch
  # this value can be changed if this name is already reserved for other systems
  # within the repository.
  #
  # Default: automated-dependencies
  #

  branch: "automated-dependencies"

jobs:
  dependencies:
    name: "Dependencies"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        shell: bash
        run: |
          git checkout -b ${{ env.branch }}

      - name: "Configure"
        run: |
          git config user.name github-actions
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: "Switch"
        run: |
          git checkout -b ${{ env.branch }}

      - name: "Updates"
        run: ./scripts/UpdateRequiredModules.ps1
        shell: pwsh

      - name: "Add"
        run: |
          git add src/AzOps.psd1

      - name: "Commit"
        run: |
          git commit -m 'Update AzOps.psd1'

      - name: "Push"
        run: |
          git push origin ${{ env.branch }}

      - name: "Merge"
        run: |
          gh pr create --base 'main' --head ${{ env.branch }} --title 'Bump Automated-Dependencies' --body '' --label 'dependencies'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}