name: 'Linter'

on:
  push:

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Linter
      uses: docker://github/super-linter:v3.14.5
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_ARM: false
        DEFAULT_BRANCH: main
        DISABLE_ERRORS: false
        FILTER_REGEX_EXCLUDE: .*.pipelines/.*
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
