name: 'Code linter'

on:
  push:

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Linter
      uses: docker://github/super-linter:v3.14.5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        DISABLE_ERRORS: false
