name: manage-azure-policy-2d3bcce7
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deny-AppGW-Without-WAF_Deny-AppGW-Without-WAF/**'
#      - 'policies/Append-Azure-HUB_Append-AzHUB/**'
#      - 'policies/Deny-Subnet-Without-NSG_Deny-Subnet-Without-Nsg/**'
#      - .github/workflows/manage-azure-policy-2d3bcce7.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2d3bcce7}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deny-AppGW-Without-WAF_Deny-AppGW-Without-WAF/**
          policies/Append-Azure-HUB_Append-AzHUB/**
          policies/Deny-Subnet-Without-NSG_Deny-Subnet-Without-Nsg/**
