---
name: "Tests"

on:
  pull_request:
  workflow_dispatch:

jobs:
  release:
    name: "Tests"
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Tests'
        run: .\scripts\Tests.ps1
        shell: pwsh