---
name: "Tests"

on:
  pull_request:

jobs:
  release:
    name: "Tests"
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Dependency'
        run: ./scripts/Dependency.ps1

      - name: 'Tests'
        run: ./scripts/Tests.ps1
        shell: pwsh