---
name: "Tests"

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.pipelines/**'
      - 'scripts/**'
      - '**.md'

jobs:
  release:
    name: "Unit Tests"
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Dependency'
        run: ./scripts/Dependency.ps1
        shell: pwsh

      - name: 'Tests'
        run: ./scripts/Tests.ps1
        shell: pwsh
